
import requests
import logging
from typing import Optional

logger = logging.getLogger(__name__)

class TelegramBot:
    """Handles sending messages and photos via the Telegram Bot API.
    """

    def __init__(self, bot_token: str, chat_id: str) -> None:
        self.bot_token = bot_token
        self.chat_id = chat_id
        self.base_url = f"https://api.telegram.org/bot{self.bot_token}"

    def send_message(self, text: str, parse_mode: str = "HTML") -> bool:
        """Sends a text message to the configured chat ID.

        Args:
            text (str): The message text to send.
            parse_mode (str): Parse mode for the message (e.g., "HTML", "MarkdownV2").

        Returns:
            bool: True if the message was sent successfully, False otherwise.
        """
        endpoint = f"{self.base_url}/sendMessage"
        payload = {
            "chat_id": self.chat_id,
            "text": text,
            "parse_mode": parse_mode
        }
        try:
            response = requests.post(endpoint, json=payload, timeout=10)
            response.raise_for_status() # Raise HTTPError for bad responses (4xx or 5xx)
            result = response.json()
            if result.get("ok"):
                logger.info("Telegram message sent successfully.")
                return True
            else:
                logger.error(f"Failed to send Telegram message: {result.get("description", "Unknown error")}")
                return False
        except requests.exceptions.RequestException as e:
            logger.error(f"Error sending Telegram message: {e}")
            return False

    def send_photo(self, photo_path: str, caption: Optional[str] = None, parse_mode: str = "HTML") -> bool:
        """Sends a photo with an optional caption to the configured chat ID.

        Args:
            photo_path (str): Local path to the photo file.
            caption (Optional[str]): Caption for the photo.
            parse_mode (str): Parse mode for the caption (e.g., "HTML", "MarkdownV2").

        Returns:
            bool: True if the photo was sent successfully, False otherwise.
        """
        endpoint = f"{self.base_url}/sendPhoto"
        payload = {
            "chat_id": self.chat_id,
            "parse_mode": parse_mode
        }
        if caption:
            payload["caption"] = caption

        try:
            with open(photo_path, "rb") as photo_file:
                files = {"photo": photo_file}
                response = requests.post(endpoint, data=payload, files=files, timeout=20)
                response.raise_for_status()
                result = response.json()
                if result.get("ok"):
                    logger.info(f"Telegram photo \'{photo_path}\' sent successfully.")
                    return True
                else:
                    logger.error(f"Failed to send Telegram photo \'{photo_path}\': {result.get("description", "Unknown error")}")
                    return False
        except FileNotFoundError:
            logger.error(f"Photo file not found: {photo_path}")
            return False
        except requests.exceptions.RequestException as e:
            logger.error(f"Error sending Telegram photo \'{photo_path}\': {e}")
            return False

if __name__ == '__main__':
    # Placeholder for actual token and chat_id from config or environment variables
    BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"
    CHAT_ID = "YOUR_CHAT_ID_HERE"

    # Setup a basic logger for example usage
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

    if BOT_TOKEN == "YOUR_BOT_TOKEN_HERE" or CHAT_ID == "YOUR_CHAT_ID_HERE":
        print("Please replace YOUR_BOT_TOKEN_HERE and YOUR_CHAT_ID_HERE with actual values to test Telegram bot functionality.")
    else:
        bot = TelegramBot(BOT_TOKEN, CHAT_ID)

        # Test sending a message
        print("\n--- Testing send_message ---")
        message_text = "<b>Test Message</b> from Trading Assistant!\n<i>This is an HTML formatted message.</i>"
        if bot.send_message(message_text):
            print("Message test initiated. Check your Telegram chat.")
        else:
            print("Message test failed.")

        # Test sending a photo (requires a dummy image file)
        print("\n--- Testing send_photo ---")
        dummy_image_path = "dummy_chart.png" # This file needs to exist for the test
        # Create a dummy image for testing
        try:
            import matplotlib.pyplot as plt
            plt.figure(figsize=(6, 4))
            plt.plot([0, 1, 2], [0, 1, 0])
            plt.title("Dummy Chart")
            plt.savefig(dummy_image_path)
            plt.close()
            print(f"Dummy image \'{dummy_image_path}\' created.")

            photo_caption = "<b>Dummy Chart</b> for BTCUSDT\n<i>Generated by Trading Assistant.</i>"
            if bot.send_photo(dummy_image_path, caption=photo_caption):
                print("Photo test initiated. Check your Telegram chat.")
            else:
                print("Photo test failed.")

            os.remove(dummy_image_path)
            print(f"Dummy image \'{dummy_image_path}\' removed.")

        except ImportError:
            print("Matplotlib not installed. Skipping dummy image creation and photo test.")
        except Exception as e:
            print(f"Could not create/send dummy image: {e}")


